version: "3.8"
services:
  backend:
    image: "fahrican/springboot-react-fullstack:26.10.2022.22.18.18"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev